# Copyright (C) PeterSuh-Q3
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Build modules with syno71.sh

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        include:
          - version: 7.1 
            platform: apollolake
            KVER: '4.4.108'
          - version: 7.1
            platform: broadwell
            KVER: '4.4.108'
          - version: 7.1 
            platform: broadwellnk
            KVER: '4.4.108'
          - version: 7.1 
            platform: bromolow
            KVER: '4.4.108'
          - version: 7.1
            platform: denverton
            KVER: '4.4.108'
          - version: 7.1 
            platform: geminilake
            KVER: '4.4.108'
          - version: 7.1
            platform: r1000
            KVER: '4.4.108'
          - version: 7.1
            platform: v1000
            KVER: '4.4.108'
          - version: 7.1 
            platform: purley
            KVER: '4.4.108'
          - version: 7.1
            platform: braswell
            KVER: '4.4.108'
          - version: 7.1 
            platform: broadwellnkv2
            KVER: '4.4.108'
          - version: 7.1 
            platform: broadwellntbap
            KVER: '4.4.108'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare workspace
        run: |
          MAJOR=$(echo "${KVER}" | cut -d. -f1)
          mkdir -p src/input src/output
          cp -a src/${MAJOR}.x/* src/input/

      - name: Grant execute on kver5.sh
        run: chmod +x src/kver5.sh

      - name: Compile modules via kver5.sh
        run: |
          cd src
          sudo ./syno71.sh 

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: src/*
          if-no-files-found: warn
