# Copyright (C) PeterSuh-Q3
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Build modules (public docker)

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  KVER: "5.10.55"
  TOOLKIT_VER: "7.2"  

jobs:
  build:
    runs-on: ubuntu-latest    
    
    strategy:
      matrix:
        include:
          - platform: v1000nk
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare Source
        run: |
          mkdir -p source/input source/output        
          MAJOR=$(echo "${KVER}" | cut -d. -f1)
          cp -a src/${MAJOR}.x/* source/input/

      - name: Compile modules with public container
        run: |
          DIR=source/input
          PLATFORM=${{ matrix.platform }}
          docker run --rm -t \
            -v "${PWD}/${DIR}":/tmp/input:rw \
            -v "${PWD}/tmp/${PLATFORM}-${KVER}":/tmp/output:rw \
            dante90/syno-compiler:${TOOLKIT_VER} \
            compile-module "${PLATFORM}"

      - name: Collect built modules
        run: |
          PLATFORM=${{ matrix.platform }}
          cp -a "tmp/${PLATFORM}-${KVER}/." source/output/
          chmod -R a+rw source/output/

      - name: Package artifacts
        run: |
          if [ -n "$(ls -A source/output)" ]; then
            tar caf source/${{ matrix.platform }}-${{ env.KVER }}.tgz -C source/output .
          else
            echo "No modules built, skipping archival."
          fi
