# Copyright (C) PeterSuh-Q3
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Build modules with kver5.sh

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  KVER: "5.10.55"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare workspace
        run: |
          MAJOR=$(echo "${KVER}" | cut -d. -f1)
          mkdir -p src/input src/output
          cp -a src/${MAJOR}.x/* src/input/

      - name: Grant execute on kver5.sh
        run: chmod +x src/kver5.sh

      - name: Compile modules via kver5.sh
        run: |
          /github/workspace/src/kver5.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: src/*
          if-no-files-found: warn
