# Copyright (C) 2022 Ing
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
# 소스 경로 수정 버전

name: Build modules (chroot)

on:
  workflow_dispatch:

env:
  # KERNEL_VERSION을 Matrix나 입력 파라미터로 정의하세요.
  KVER: "5.10.55"

jobs:
  build:
    container: ghcr.io/petersuh-q3/arpl-modules-multi:7.2-v1000nk  
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        include:
          - version: "7.2"
            platform: v1000nk
            
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Init Env
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Seoul"

      - name: Get Src
        run: |
          MAJOR=$(echo "${{ env.KVER }}" | cut -d. -f1)
          cp -a src/${MAJOR}.x source/input

      - name: Build Modules inside Chroot
        run: |
          sudo chroot /opt/build_env/ds.${{ matrix.platform }}-${{ matrix.version }} << 'EOF'
            # chroot 내부에서 빌드
            cd /source/input
            make -j$(nproc) M=$(pwd) modules
          EOF

          # 빌드된 모듈(.ko) 스트립 및 복사
          while read F; do
              strip -g "${F}"
              echo "Copying $(basename ${F})"
              cp "${F}" "/source/output"
          done < <(find . -name '*.ko')
          EOF

          # 빌드 결과물을 호스트로 복사
          sudo cp -a ${ROOT_PATH}/build_env/ds.${{ matrix.platform }}-${{ matrix.version }}/source/output/. ${ROOT_PATH}/source/output/
          sudo chmod a+rw -R ${ROOT_PATH}/source/output

      - name: Tar to Artifacts
        run: |
          ROOT_PATH=${{ github.workspace }}
          PARTY3RD_PATH="${ROOT_PATH}/thirdparty/${{ matrix.platform }}-${{ env.KVER }}"
          [ -d "${PARTY3RD_PATH}" ] && cp -rf "${PARTY3RD_PATH}/." "${ROOT_PATH}/source/output"

          # 빌드된 파일이 있을 경우에만 아카이브 생성
          if [ -n "$(ls -A ${ROOT_PATH}/source/output)" ]; then
            sudo tar caf ${ROOT_PATH}/source/${{ matrix.platform }}-${{ env.KVER }}.tgz -C ${ROOT_PATH}/source/output .
          else
            echo "No modules built, skipping archival."
          fi

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modules
          path: ${{ github.workspace }}/source/*.tgz
          if-no-files-found: warn
