name: Tar modules epyc7002

on:
  workflow_dispatch:

jobs:
  tar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tar modules
        run: |
          ls -d *-*/ | grep epyc7002
          for D in `ls -d *-*/ | grep epyc7002`; do
            E=$(echo ${D} | sed 's#/##')

            #echo "backup ${E} tcrp modules"
            #for file in "$E"/*.ko; do
            #  if [ -f "$file" ]; then
            #    new_name="${file}.bak"
            #    mv -vf "$file" "$new_name"                
            #  fi
            #done
            
            echo "download last rr ${E} module pack"
            curl -kL https://github.com/PeterSuh-Q3/arpl-modules/releases/download/rr-last/${E}.tgz -o /tmp/${E}.tgz
            echo "extract last rr ${E} module pack"
            mkdir -p /tmp/${E}/
            tar -xaf /tmp/${E}.tgz -C /tmp/${E}/
            
            echo "copy ${E} rr modules to tcrp if module not exists"
            for fullpath in /tmp/"$E"/*.ko; do
                file=$(basename "$fullpath")
                [ ! -f ./${E}/"$file" ] && cp -vf "$fullpath" ./${E}/"$file" || echo "$file Already exists..."
            done
            
            #echo "restore ${E} tcrp modules"
            #for file in "$E"/*.ko.bak; do
            #  if [ -f "$file" ]; then
            #    new_name="${file%.bak}"
            #    [ ! -f "$new_name" ] && mv -vf "$file" "$new_name" || rm -vf "$file"
            #  fi
            #done

            echo "copy ${E} vanilla module"
            [ -d ./vanilla/${E} ] && cp -vf ./vanilla/${E}/*.ko ./${E}/
            #echo "copy ${E} thirdparty module" # i915.ko Already have in RR
            #[ -d ./thirdparty/${E} ] && cp -vf ./thirdparty/${E}/*.ko ./${E}/
            (cd ${E} && tar caf ../${E}.tgz *)
            sha256sum ./${E}.tgz | awk '{print $1}' | awk '{print $1 " '${E}.tgz' modpack.sha256"}' >> files-chksum
          done
          
          cat files-chksum

          mkdir -p /opt/repack
          cp -vf files-chksum /opt/repack
          cp -vf epyc7002*.tgz /opt/repack
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: module-repack 
          path: /opt/repack
