name: Tar modules single

on:
  workflow_dispatch:

jobs:
  tar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Tar modules
        run: |
          git clone https://github.com/wjz304/arpl-modules.git
          ls -d broadwellnk-4.4.302/
          for D in `ls -d broadwellnk-4.4.302`; do
            E=$(echo ${D} | sed 's#/##')
            if [ ${E} == "epyc7002-5.10.55" ]; then
              mkdir -p /tmp/${E}
              mv -f ./${E}/*.ko /tmp/${E}/
              echo "merge wjz304's official ${E}"
              cp -vf ./arpl-modules/official/${E}/*.ko ./${E}/
              echo "merge wjz304's thirdparty ${E}"              
              [ -f ./arpl-modules/thirdparty/${E} ] && cp -vf ./arpl-modules/thirdparty/${E}/*.ko ./${E}/
            else 
              echo "merge wjz304's official ${E}"
              cp -vf ./arpl-modules/official/${E}/*.ko ./${E}/
              echo "merge wjz304's thirdparty ${E}"              
              [ -f ./arpl-modules/thirdparty/${E} ] && cp -vf ./arpl-modules/thirdparty/${E}/*.ko ./${E}/
              echo "copy ${E} vanilla module"              
              [ -f ./vanilla/${E} ] && cp -vf ./vanilla/${E}/*.ko ./${E}/
            fi
            (cd ${E} && tar caf ../${E}.tgz *.ko)
            sha256sum ./${E}.tgz | awk '{print $1}' | awk '{print $1 " '${E}.tgz' files.sha256"}' >> files-chksum
          done
          cat files-chksum
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${E}-repack 
          path: ./
