name: Tar modules single

on:
  workflow_dispatch:

jobs:
  tar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Tar modules
        run: |
          ls -d bromolow-3.10.108/
          for D in `ls -d bromolow-3.10.108`; do
            E=$(echo ${D} | sed 's#/##')
            echo "copy ${E} vanilla module"              
            [ -d ./vanilla/${E} ] && cp -vf ./vanilla/${E}/*.ko ./${E}/
            (cd ${E} && tar caf ../${E}.tgz *.ko)
            sha256sum ./${E}.tgz | awk '{print $1}' | awk '{print $1 " '${E}.tgz' files.sha256"}' >> files-chksum
          done
          cat files-chksum
          mkdir -p /opt/repack
          cp -vf files-chksum /opt/repack
          cp -vf ${E}.tgz /opt/repack
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: module-repack 
          path: /opt/repack

